# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fofa_help.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Fofa_Help(object):
    def setupUi(self, Fofa_Help):
        Fofa_Help.setWindowFlags(QtCore.Qt.WindowStaysOnTopHint)
        Fofa_Help.setObjectName("Fofa_Help")
        Fofa_Help.resize(725, 822)
        self.verticalLayout = QtWidgets.QVBoxLayout(Fofa_Help)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_FOFA_Help = QtWidgets.QTableWidget(Fofa_Help)
        self.tableWidget_FOFA_Help.setObjectName("tableWidget_FOFA_Help")
        self.tableWidget_FOFA_Help.setColumnCount(0)
        self.tableWidget_FOFA_Help.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget_FOFA_Help)

        # self.tableWidget_FOFA_Help.horizontalHeader().set
        self.retranslateUi(Fofa_Help)
        QtCore.QMetaObject.connectSlotsByName(Fofa_Help)

    def retranslateUi(self, Fofa_Help):
        _translate = QtCore.QCoreApplication.translate
        Fofa_Help.setWindowTitle(_translate("Fofa_Help", "FOFA帮助信息"))
